/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memoryanalyzer;

import java.awt.Point;
import java.awt.GraphicsEnvironment;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import org.jfree.chart.ChartPanel;
import analyzer.ViewerThread;
import common.MsgBox;
import common.WaitBox;
import crossplatform.Help;

/**
 *
 * @author master
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        
        // If user OS isn't supported then show message
        if(Help.GetOS().equals(Help.ERR_UNKNOWN_OS)) {
            errorUnknownSystem();
        }
        // Check: is pin installed? If yes then run the pin server
        pinServerProcess = null;
        if(!Help.isPinInstalled()) {
            new MsgBox(this, "Warning!", "Intel PIN is not installed!\n"
                    + "Local analysis is not available!",
                    MsgBox.ACTION_OK).setVisible(true);
        }
        else {
            try {
                pinServerProcess = Help.runPinServer();
            } catch(IOException ex) {
                new MsgBox(this, "Warning!", ex.getMessage(),
                        MsgBox.ACTION_OK).setVisible(true);
            }
        }
        // Init chooser
        initResultsChooser();
        // Initialization current chart as null
        chart = null;
        tmpResultsFileName = null;
        // Create special form for connection
        formConnectTo = new FormConnectTo(this, pinServerProcess != null);
        setCenterLocation();
    }
    
    public void updateChart(ChartPanel newChart) {
        chart = newChart;
        chart.setSize(jPanel4Chart.getSize());
        // If chart already was on a panel then remove it 
        jPanel4Chart.removeAll();
        // Revalidate a panel
        jPanel4Chart.revalidate();
        // Add new chart on a panel
        jPanel4Chart.add(chart);
        repaint();
    }
    
    public void clearChart() {
        deleteTmpResultsFile();
        chart = null;
        jPanel4Chart.removeAll();
        jPanel4Chart.revalidate();
        repaint();
    }

    public String getTmpResultsFileName() {
        tmpResultsFileName = Help.GetBinaryResultsPath();
        return tmpResultsFileName;
    }
    
    private void initResultsChooser() {
        String binaryFileExtension = Help.GetBinaryFileExtension();
        resultsChooser = new JFileChooser();
        resultsChooser.setMultiSelectionEnabled(false);
        FileNameExtensionFilter filterNameExtension;
        filterNameExtension = new FileNameExtensionFilter("Binary output (*"
            + binaryFileExtension + ")", binaryFileExtension.replaceAll("\\.", ""));
        resultsChooser.removeChoosableFileFilter(resultsChooser.getChoosableFileFilters()[0]);
        resultsChooser.addChoosableFileFilter(filterNameExtension);
    }
    
    private void errorUnknownSystem()
    {
        new MsgBox(this, "Error!", "Your operating system is not supported!",
            MsgBox.ACTION_CLOSE).setVisible(true);
    }
    
    private void setCenterLocation()
    {
        Point p = GraphicsEnvironment.getLocalGraphicsEnvironment().getCenterPoint();
        this.setLocation(p.x - this.getWidth() / 2, p.y - this.getHeight() / 2);
    }
    
    private void deleteTmpResultsFile() {
        if(tmpResultsFileName != null) {
            try {
                Files.deleteIfExists(Paths.get(tmpResultsFileName));
            } catch (IOException ex) {
                // DO NOTHING
            }
        }
        tmpResultsFileName = null;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel4Chart = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemOpenApp = new javax.swing.JMenuItem();
        jMenuItemOpenResults = new javax.swing.JMenuItem();
        jMenuItemSaveBinFile = new javax.swing.JMenuItem();
        jMenuItemClose = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MemoryAnalyzer");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4ChartLayout = new javax.swing.GroupLayout(jPanel4Chart);
        jPanel4Chart.setLayout(jPanel4ChartLayout);
        jPanel4ChartLayout.setHorizontalGroup(
            jPanel4ChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );
        jPanel4ChartLayout.setVerticalGroup(
            jPanel4ChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        jMenuFile.setText("File");
        jMenuFile.setFont(new java.awt.Font("Ubuntu", 0, 16)); // NOI18N

        jMenuItemOpenApp.setText("New Test...");
        jMenuItemOpenApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenAppActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemOpenApp);

        jMenuItemOpenResults.setText("Open Results...");
        jMenuItemOpenResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenResultsActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemOpenResults);

        jMenuItemSaveBinFile.setText("Save Results as a Binary File...");
        jMenuItemSaveBinFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveBinFileActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemSaveBinFile);

        jMenuItemClose.setText("Close Results");
        jMenuItemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCloseActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemClose);

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar.add(jMenuFile);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4Chart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4Chart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemOpenAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenAppActionPerformed
        formConnectTo.setVisible(true);
    }//GEN-LAST:event_jMenuItemOpenAppActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemOpenResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenResultsActionPerformed
        resultsChooser.setDialogTitle("Open Results...");
        int ret = resultsChooser.showOpenDialog(this);
        if(ret != JFileChooser.APPROVE_OPTION) {
            return;
        }
        File resultsFile = resultsChooser.getSelectedFile();
        if(resultsFile == null || !resultsFile.exists()) {
            return;
        }
        clearChart();
        ViewerThread viewerThread = new ViewerThread(this, resultsFile.getAbsolutePath());
        WaitBox threadWaitBox = new WaitBox("Reading of file...");
        threadWaitBox.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        threadWaitBox.setVisible(true);
        threadWaitBox.start(viewerThread);
    }//GEN-LAST:event_jMenuItemOpenResultsActionPerformed

    private void jMenuItemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCloseActionPerformed
        clearChart();
    }//GEN-LAST:event_jMenuItemCloseActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        if(chart != null) {
            chart.setSize(jPanel4Chart.getSize());
        }
    }//GEN-LAST:event_formComponentResized

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        deleteTmpResultsFile();
        formConnectTo.setVisible(false);
        formConnectTo.dispose();
        this.setVisible(false);
        this.dispose();
        if(pinServerProcess != null) {
            pinServerProcess.destroy();
        }
        System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    private void jMenuItemSaveBinFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveBinFileActionPerformed
        if(tmpResultsFileName == null || !Files.exists(Paths.get(tmpResultsFileName))) {
            new MsgBox(this, "Notice", "No data to save!",
                MsgBox.ACTION_OK).setVisible(true);
            return;
        }
        resultsChooser.setDialogTitle("Save Results...");
        int ret = resultsChooser.showSaveDialog(this);
        if(ret != JFileChooser.APPROVE_OPTION) {
            return;
        }
        File resultsFile = resultsChooser.getSelectedFile();
        if(resultsFile != null) {
            try {
                String resultsAbsPath = resultsFile.getAbsolutePath().replace(
                        Help.GetBinaryFileExtension(), "") + Help.GetBinaryFileExtension();
                Files.deleteIfExists(Paths.get(resultsAbsPath));
                Files.move(Paths.get(tmpResultsFileName), Paths.get(resultsAbsPath));
                tmpResultsFileName = null;
            } catch (IOException ex) {
                new MsgBox(this, "Error!", "Unable to save data!",
                    MsgBox.ACTION_OK).setVisible(true);
            }
        }        
    }//GEN-LAST:event_jMenuItemSaveBinFileActionPerformed

    // Private variables
    private final FormConnectTo formConnectTo;
    private Process pinServerProcess;
    private JFileChooser resultsChooser;
    private ChartPanel chart;
    private String tmpResultsFileName;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemClose;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemOpenApp;
    private javax.swing.JMenuItem jMenuItemOpenResults;
    private javax.swing.JMenuItem jMenuItemSaveBinFile;
    private javax.swing.JPanel jPanel4Chart;
    // End of variables declaration//GEN-END:variables
}
