/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memoryanalyzer;

import java.awt.GraphicsEnvironment;
import java.awt.Point;
import javax.swing.JFrame;

/**
 *
 * @author master
 */
public class MsgBox extends javax.swing.JFrame {

    public final static int ACTION_OK = 0;
    public final static int ACTION_CLOSE = 1;

    public MsgBox(JFrame retJFrame, String title, String message, int KEY_ACTION) {
        initComponents();
        //Set properties the MsgBox
        InitMsgBox(title, message);
        //Remember return frame
        this.retJFrame =  retJFrame;
        //Remember action key
        this.key_action = KEY_ACTION;
        //If frame feedback was enabled then code below changes state
        if(!retJFrame.isEnabled()) {
            lock = false;
        }
        else {
            lock = true;
            retJFrame.setEnabled(false);
        }
        retJFrame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        //Remember size of label
        heightOfLabelMessage = jLabelMessage.getHeight();
    }
    private void InitMsgBox(String title, String message)
    {
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setTitle(title);
        String multiline_text = ConvertToMultiline(message);
        this.jLabelMessage.setText(multiline_text);
        this.jLabelMessage.setToolTipText(multiline_text);
        this.setCenterPosition();
    }
    private String ConvertToMultiline(String line)
    {
        return "<html><p align=\"center\">" + line.replaceAll("\n", "<br>") + "</p></html>";
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonOk = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(300, 500));
        setMinimumSize(new java.awt.Dimension(300, 100));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButtonOk.setText("OK");
        jButtonOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOkMouseClicked(evt);
            }
        });

        jLabelMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMessage.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelMessage.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jLabelMessageComponentResized(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOk)
                .addGap(128, 128, 128))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonOk)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void setCenterPosition()
    {
        Point p = GraphicsEnvironment.getLocalGraphicsEnvironment().getCenterPoint();
        this.setLocation(p.x - this.getWidth() / 2, p.y - this.getHeight() / 2);
    }
    
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        switch(key_action) {
            case ACTION_CLOSE:
                //Close feedback
                retJFrame.setVisible(false);
                retJFrame.dispose();
                break;
            default:
                //Enable a frame which called the MsgBox
                if(lock) {
                    retJFrame.setEnabled(true);
                }
                retJFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                break;
        }
    }//GEN-LAST:event_formWindowClosed

    private void jButtonOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOkMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jButtonOkMouseClicked

    private void jLabelMessageComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLabelMessageComponentResized
        this.setSize(this.getWidth(), this.getHeight()
                + jLabelMessage.getHeight() - heightOfLabelMessage);
        heightOfLabelMessage = jLabelMessage.getHeight();
        this.setCenterPosition();
    }//GEN-LAST:event_jLabelMessageComponentResized
    
    // My variables
    private final JFrame retJFrame;
    private final int key_action;
    private final boolean lock;
    private int heightOfLabelMessage;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelMessage;
    // End of variables declaration//GEN-END:variables
}
