/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memoryanalyzer;

import java.awt.GraphicsEnvironment;
import java.awt.Point;
import javax.swing.JFrame;
import memoryanalyzer.WaitBoxThread.WaitBoxFeedback;

/**
 *
 * @author master
 */
public class WaitBox extends javax.swing.JFrame {

    /**
     * Creates new form WaitBox
     * @param retJFrame
     */
    public WaitBox(JFrame retJFrame) {
        initComponents();
        resetParameters();
        // Save feedback
        this.retJFrame = retJFrame;
        setCenterPosition();
    }
    
    private void resetParameters() {
        waitBoxFeedback = null;
        waitBoxThread = null;
    }
    
    private void setCenterPosition() {
        Point p = GraphicsEnvironment.getLocalGraphicsEnvironment().getCenterPoint();
        this.setLocation(p.x - this.getWidth() / 2, p.y - this.getHeight() / 2);
    }
    
    public void updateProgress() {
        if(waitBoxFeedback != null) {    
            jProgressBar.setValue(waitBoxFeedback.progress);
        }
    }
    
    public boolean waitingStart() {
        // Disabled feedback
        retJFrame.setEnabled(false);
        if(waitBoxThread != null) {
            return false;
        }
        else {
            waitBoxFeedback = new WaitBoxFeedback();
            waitBoxFeedback.wait = true;
            waitBoxFeedback.progress = 0;
            waitBoxThread = new WaitBoxThread(this, waitBoxFeedback);
            waitBoxThread.start();
            return true;
        }
    }
    
    public void waitingStop() {
        if(waitBoxFeedback != null) {
            waitBoxFeedback.wait = false;
        }
        // Enabled feedback until before a thread
        retJFrame.setEnabled(true);
        resetParameters();
    }
    
    private final JFrame retJFrame;
    private WaitBoxFeedback waitBoxFeedback;
    private WaitBoxThread waitBoxThread;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar = new javax.swing.JProgressBar();
        jLabelState = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Waiting");
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setMaximumSize(new java.awt.Dimension(320, 70));
        setMinimumSize(new java.awt.Dimension(320, 70));
        setPreferredSize(new java.awt.Dimension(320, 70));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jProgressBar.setMaximumSize(new java.awt.Dimension(290, 20));
        jProgressBar.setMinimumSize(new java.awt.Dimension(290, 20));
        jProgressBar.setPreferredSize(new java.awt.Dimension(290, 20));

        jLabelState.setText("Capture info...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelState)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelState, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        waitingStop();
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelState;
    private javax.swing.JProgressBar jProgressBar;
    // End of variables declaration//GEN-END:variables
}
